version: "3"
services:
  hello-service:
    image: gcr.io/docker-jib-multi/hello-service:0.1.0
    ports:
      - "8081:8081"
    networks:
      - hello-name
    depends_on:
      - name-service

  name-service:
    image: gcr.io/docker-jib-multi/name-service:0.1.0
    ports:
      - "8080:8080"
    networks:
      - hello-name

networks:
  hello-name: